<?php

namespace African\UserBundle\Repository;

/**
 * SubcriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcriberRepository extends \Doctrine\ORM\EntityRepository
{
}
